version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/online-shopper-segmentation-streamlit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Project_18_Online_Shopper_Segmentation_Streamlit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/amazon-review-marketing-intelligence"
    schedule:
      interval: "weekly"
