name: portfolio-python
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools<81
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pip:
      - tpot
